package.json
yarn.lock

:heavy_plus_sign: Added chakraUI

---

src/components/header.tsx
src/components/layout.tsx
src/components/navbar.tsx
src/styles/globalTheme.js

added grey palette in theme as well

:art: Improved code structure of header/navbar, some color mode things

---

gatsby-config.js
gatsby-ssr.js
package.json
src/components/event.tsx
src/components/eventBox.tsx
src/components/footer.tsx
src/components/header.tsx
src/components/layout.tsx
src/components/navbar.tsx
src/gatsby-plugin-chakra-ui/theme.js
src/markdown.js
src/templates/blogPost.tsx
yarn.lock

Upgraded and fixed dependencies

:arrow_up: Upgraded to chakraui 1.0.0

---

src/pages/omoss.tsx

Begynt paa om omoss-siden, lagt til "tabs" som er dynamiske til sidens-størrelse.

Feature/omoss -> omoss

---

.github/workflows/dev_test.yml

👷 Added Github Action for testing

---

package.json
yarn.lock

Fixes a security vulnerability caused by axios < 0.21.1

⬆️ Bump contentful from 7.14.13 to 8.1.7

---

.eslintrc.js

Added no console rule

---

package.json
src/components/__tests__/navbar.test.tsx
src/lib/api/api.ts
src/lib/api/event.ts
src/lib/api/post.ts
src/pages/events/[slug].tsx
src/pages/posts/[slug].tsx
yarn.lock

Added a better implementation of the contentful API, see #48

feature/api -> develop

---

src/pages/events/[slug].tsx
src/pages/posts/[slug].tsx

Fixed the bug described in #53

:bug: Fixed title rendering bug

---

src/lib/api/__tests__/bedpres.test.ts
src/lib/api/__tests__/mock-responses.ts
src/lib/api/bedpres.ts
src/lib/api/index.ts
src/lib/api/schema.ts
src/lib/types/bedpres.ts
src/lib/types/index.ts
src/pages/bedpres/[slug].tsx

Implemented bedpres:
* content type
* page
* data fetching via API
* tests
closes #61

Bedpres page, content type and data fetching

---

renovate.json

🔧 Added stabilityDays to Renovate Bot config

---

public/static/om-oss/hvem-er-vi.md
src/lib/api/index.ts
src/lib/api/minute.ts
src/lib/api/schema.ts
src/lib/types/index.ts
src/lib/types/minute.ts
src/pages/for-bedrifter.tsx
src/pages/for-studenter.tsx
src/pages/om-oss.tsx

Implemented meeting minutes. Grabs every meeting minute from contentful and links them at /om-oss.

Meeting minutes

---

package.json
src/components/bedpres-block.tsx
src/components/events-block.tsx
src/pages/_app.tsx
src/pages/index.tsx
yarn.lock

Added progress bar when changing route using nprogress.

Added progress bar

---

src/components/bedpres-block.tsx
src/lib/api/bedpres.ts
src/lib/api/schema.ts
src/pages/index.tsx

Hotfix bedpres query, post content model

---

src/components/bedpres-block.tsx
src/lib/api/bedpres.ts
src/lib/api/schema.ts
src/pages/index.tsx

Updated post content model for master, didn't have thumbnail previously.
Fixed bedpres query. Date filtering is now handled on the client side, please check code diff.

Fixed bedpres query, and posts content model

---

src/components/bedpres-block.tsx

Merge to develop, same as #161

Hotfix error message

---

src/components/bedpres-block.tsx
src/pages/index.tsx

Fixed a bug where index only fetches the 3 first bedpreses.

:ambulance: Fixed index only fetching 3 bedpreses

---

src/components/events-block.tsx
src/components/header.tsx
src/components/navbar.tsx
src/components/post-preview.tsx
src/pages/bedpres/[slug].tsx
src/pages/events/[slug].tsx
src/pages/om-oss.tsx
src/pages/posts/[slug].tsx

Refactored icons to how they should be implemented. See [this](https://chakra-ui.com/docs/media-and-icons/icon).

:recycle: Fixed chakra icons

---

src/pages/404.tsx

✨ Added a nicer 404 page

---

src/components/footer.tsx

Improved footer styling

---

src/components/bedpres-block.tsx
src/components/error-box.tsx
src/components/events-block.tsx
src/components/post-list.tsx
src/components/student-group-section.tsx
src/lib/api/bedpres.ts
src/lib/api/errors.ts
src/lib/api/event.ts
src/lib/api/minute.ts
src/lib/api/post.ts
src/lib/api/schema.ts
src/lib/api/student-group.ts
src/pages/bedpres/[slug].tsx
src/pages/bedpres/index.tsx
src/pages/events/[slug].tsx
src/pages/for-studenter.tsx
src/pages/index.tsx
src/pages/om-oss.tsx
src/pages/posts/[slug].tsx

Implemented some basic error handling, please see code.
- :construction: Error handling
- :construction: Catching the errors
- :bug: Fixed an API bug
- :goal_net: Update errors

Error handling

---

package.json
src/pages/_app.tsx
yarn.lock

Added a better progressbar, easier to customize, and made for next.
Please check out ![](https://github.com/apal21/nextjs-progressbar)

Better Progressbar

---

src/components/bedpres-block.tsx
src/components/event-preview.tsx
src/components/events-block.tsx
src/components/post-block.tsx
src/lib/api/event.ts
src/lib/api/schema.ts
src/pages/bedpres/index.tsx
src/pages/events/index.tsx
src/pages/index.tsx

Added events page.
Better bedpres and event sorting.
- :sparkles: Added events page
- :fire: Removed unused imports

Events page

---

src/components/post-card.tsx

titles should now display properly. Also changed the colors and hovercolors of post-card to something a bit more pleasant

:lipstick: fixed titles in post-card always ending in '...'

---

.gitignore
src/lib/generateRssFeed.js
src/lib/generateRssFeed.tsx
src/pages/index.tsx

Implemented RSS-feed!
When live, can be found at [https://echo.uib.no/rss.xml](https://echo.uib.no/rss.xml)
- :sparkles: Basic rss functionality
- :label: Rewrote rss generator in typescript

Implemented rss

---

src/components/navbar.tsx

should improve the user experience a bit

:lipstick: Navbar now shows active link as selected

---

.husky/pre-commit
src/components/__tests__/event-block.test.tsx
src/components/__tests__/post-block.test.tsx
src/components/bedpres-block.tsx
src/components/bedpres-preview.tsx
src/components/event-block.tsx
src/components/event-preview.tsx
src/components/member-profile.tsx
src/components/post-block.tsx
src/components/post-list.tsx
src/components/post-preview.tsx
src/pages/bedpres/index.tsx
src/pages/events/index.tsx
src/pages/index.tsx
src/pages/posts/index.tsx

Rename 'events-block' -> 'event-block' and 'post-card' -> 'post-preview'. Fixed pre-commit hook not running tests. Changed colors in post-preview so posts on /post don't have the exact same color as the background.

✅ Add tests for event-block and post-block

---

src/components/post-list.tsx
src/pages/posts/index.tsx

Added a parameter for how many posts are on each page.

🐛 Fix bug where posts show up on multiple pages

---

src/components/bedpres-form.tsx
src/components/bedpres-view.tsx
src/lib/api/registration.ts
src/pages/bedpres/[slug].tsx

Also admin view is its own component now.

🎨 Add waitlist and refactor responses

---

package.json
yarn.lock

➖ Remove identity-obj-proxy

---

.github/workflows/create_pr.yaml
.github/workflows/cypress_test_dev.yaml
.github/workflows/cypress_test_prod.yaml
.github/workflows/jest_test.yaml
.github/workflows/release_tag.yaml
Dockerfile
README.md
docker-compose.yaml
package.json
yarn.lock

Removed `wait-on`, no longer used. Also rename reference to `test_scripts`
-> `scripts` to reflect changes on backend. Cypress now tests against
both develop and production backend.

♻️ Refactor workflows

---

src/components/countdown.tsx
src/pages/bedpres/[slug].tsx

button was visible before registration time

🐛 Fixed a bedpres registration bug

---

src/lib/generate-rss-feed.ts

bedpres will now notify the day of registration

🐛 Fixed rss notification bug

---

src/components/countdown.tsx
src/components/happening.tsx
src/lib/hooks/use-countdown.ts
src/pages/bedpres/[slug].tsx
src/pages/events/[slug].tsx

- 🚑 Move date handling for countdown to server side
- Fix broken parameter
- 🐛 Fixed countdown checking server timestamp
- 🚨 Fixed unused imports
- 🍻 countdown hook server side timestamp
- 🔊 Test
- 🔥 Scheisse
- 🔥 utc string sa du?
- 🚀 Gefahren ja
- 🍻 Should be good?
- 🎨 Sneiks bri
- ⏪ Revert to client side countdown

Hotfix to develop

---

.dockerignore
.github/workflows/cypress_test_dev.yaml
.github/workflows/cypress_test_prod.yaml
.github/workflows/jest_test.yaml
docker-compose.ci.yaml

Now 100% faster :zap: :zap: :zap:

💚 Add cache to workflows for faster CI

---

src/pages/index.tsx

:bug: Front page now only displays 3 bedpreses

---

src/components/happening-meta-info.tsx

🐛 Fixed a bug where total spots doesn't show up before registration opens

---

.env.example
.github/workflows/cypress_test_dev.yaml
.github/workflows/cypress_test_prod.yaml
docker-compose.ci.yaml
docker-compose.yaml
src/lib/api/registration.ts
src/pages/bedpres/[slug].tsx
src/pages/events/[slug].tsx

♻️ Combine BEDKOM_KEY and WEBKOM_KEY to single env

---

src/components/happening-meta-info.tsx
src/components/happening.tsx

Default value for min and max degree year was wrong, and should not show year on registration when there is only one spot range. Also add some null checks.

🐛 Fix conditionals on happening meta info text

---

src/components/happening-meta-info.tsx

See https://echo.uib.no/bedpres/knowit.

🐛 Fix degree year not showing on split registration

---

src/components/happening-meta-info.tsx

On happenings where no one has registered and only one spot range, see https://echo-uib-no-git-develop-echo-webkom.vercel.app/events/shiiiiiii.

🐛 Fix year showing unnecessarily on happening

---

src/components/form-question.tsx
src/components/form-term.tsx
src/components/registration-form.tsx

Move questions and terms to own components/files.

♻️ Refactor registration form

---

package.json

💄 Add emoji to start of Renovate commits and PR's

---

src/components/header.tsx

Add sprutnice

---

src/components/color-mode-button.tsx
src/components/navbar.tsx

Worlds colormode complexity drops to 0

💄 Cooler colormode button :sunglasses:

---

package.json
src/components/__tests__/testing-wrapper.tsx
src/components/layout.tsx
yarn.lock

<h1> 
\> Removes `prop-types`
\> Makes pull request
\> Refuses to eloborate further
\> Leaves
</h1>

➖ Remove prop-types

---

.github/workflows/cypress_test.yaml
.github/workflows/jest_test.yaml
.github/workflows/lint_format.yaml
.lintstagedrc.js
docker-compose.ci.yaml
docker-compose.yaml
package.json

Nice med litt redudancy selv om dette (teknisk sett) skal skje hver gang man commiter.
La også til automatisk formattering for `yaml`-filer.
EDIT: også nice for å se om `eslint` eller `prettier` breaker når Renovate oppgraderer de.

🚀 Add lint & format action and yaml format

---

src/markdown.ts
src/styles/themes/halloween-theme.ts
src/styles/themes/main-theme.ts

🏷️ JavaScript -> TypeScript

---

src/components/happening-meta-info.tsx
src/components/happening.tsx

Nå står det 'Avmelding' i stedet for bare en random mail.

🚸 Easier to understand UI

---

.github/workflows/rebase.yaml

Nå kan du kommentere "/rebase" på en pull request som er out of date, så vil den automatisk hente inn nye endringer :)

🚀 Add action for auto-rebasing pull request

---

package.json
src/components/__tests__/testing-utils.js
src/components/happening-meta-info.tsx
src/components/header.tsx
src/components/minute-list.tsx
src/components/registration-form.tsx
src/lib/api/api.ts
src/lib/api/happening.ts
src/lib/api/index.ts
src/lib/api/minute.ts
src/lib/api/post.ts
src/lib/api/registration.ts
src/lib/api/student-group.ts
src/pages/bedpres/[slug].tsx
src/pages/events/[slug].tsx
src/pages/index.tsx
src/pages/om-oss.tsx
src/pages/posts/[slug].tsx

Nå fikser eslint automatisk riktig rekkefølge på imports og exports.

♻️ Add lint errors for imports/exports

---

src/pages/posts/[slug].tsx

now matchin design of happenings

💄 Update post meta info

---

src/components/layout.tsx

once again :)
**Before:**
**After:**

🐛 Fixed footer margin

---

src/components/hsp.tsx

💄 Fix misaligned boxes

---

package.json
src/components/happening.tsx
src/lib/api/happening.ts

🎨 Add more eslint rules

---

src/components/footer.tsx
src/components/header.tsx
src/components/layout.tsx
src/components/navbar.tsx

- La til en maks bredde på layout, sånn at boksene ikke blir super bred om man har en skjerm av høyere oppløsning.
- Flyttet også navbar til høyre side av header.
- La også til "Vim eller forsvinn" som header-melding.
- Linkene er også til venstre i drawer menyen, samme side som teksten "Navigasjon".
~~Footer som før, siden jeg ikke orket å tulle med den.~~
**Edit:** Den ble tullet med.
<details>
<summary>Før</summary>
<br>
</details>
<details>
<summary>Etter</summary>
<br>
</details>

:lipstick: Added max width and navbar aligned to right side

---

src/components/happening-meta-info.tsx

Spots < 1 gir uendelig plasser.
Hører sammen med https://github.com/echo-webkom/echo-web-backend/pull/201.

✨ Spot ranges with infinite spots

---

src/components/happening-meta-info.tsx

🐛 Fix spotsText not returning

---

src/components/happening-meta-info.tsx

🐛 Fix spotsText ternary

---

src/components/happening-meta-info.tsx

🐛 Fix showing 0 registrations for infinite spots

---

src/components/__tests__/happening-meta-info.test.tsx
src/components/happening-meta-info.tsx

✅ Add tests for happening-meta-info

---

next-env.d.ts
src/components/button-link.tsx
src/lib/api/errors.ts
src/lib/api/index.ts
src/lib/api/registration.ts
src/pages/registration/[slug].tsx

Gjør at påmeldingslistene ser mye bedre ut siden vi kan bruke React & Chakra istedenfor HTML & CSS (som vi har brukt hittil via
backend). Gir også mer mening å se listene på echo.uib.no.

✨ Add admin page for viewing registrations

---

src/components/entry-box.tsx
src/components/entry-list.tsx
src/components/nav-link.tsx
src/components/seo.tsx

Se https://github.com/facebook/react/pull/16210.

♻️ Remove 'defaultProps' as it will be deprecated

---

.github/workflows/cypress_test.yaml
docker-compose.ci.yaml

🚀 Move from Docker Hub to GHCR

---

.github/workflows/cypress_test.yaml
docker-compose.ci.yaml

GHCR fucker seg om flere repo'er pusher samme image (package). Er også unødvendig å bygge på nytt, kan bare pulle eksisterende image fra GHCR.
Matcher https://github.com/echo-webkom/echo-web-backend/pull/243/commits/3867e6ce4f7217d043c01ca2f1e21bae154d0ad8 fra backend.

♻️ Build & push only frontend image

---

package.json
yarn.lock

1.7.4 fikk alt til å se styggere ut, dette er en quickfix.

⬇️ Downgrade @chakra-ui/react to 1.7.3

---

src/components/button-link.tsx
src/components/entry-box.tsx
src/components/post-block.tsx
src/components/post-list.tsx
src/pages/posts/index.tsx
src/pages/registration/[slug].tsx

Added query parameters for posts
Url will now be like this: `/posts?page=2`
Also refactored `PostList` and `index` for posts. As well as `ButtonLink`, it now accepts chakra props (just like `Section`).

Query params for posts

---

src/components/__tests__/student-group-section.test.tsx
src/components/student-group-section.tsx
src/lib/api/decoders.ts
src/lib/api/post.ts
src/lib/api/student-group.ts
src/pages/for-studenter/[slug].tsx
src/pages/for-studenter/index.tsx

`/for-studenter/webkom`, osv...
Ser kanskje ikke helt optimalt ut, men det kan fikses senere evt.

🎨 Move student groups to their own pages

---

src/components/__tests__/info-panels.test.tsx
src/components/info-panels.tsx
src/pages/for-bedrifter.tsx
src/pages/for-studenter/index.tsx
src/pages/om-oss.tsx

Tenker ikke det har en dritt å si egt, er legit 1 kb med tekst som må lastes fra Vercel.
Tror ikke `next/router` funker med `getStaticProps` så vidt jeg skjønte.

✨ Sub routes on /for-studenter

---

src/components/happening-page.tsx
src/pages/bedpres/[slug].tsx
src/pages/event/[slug].tsx

♻️ Move identical pages to own component

---

.husky/pre-commit

Unødvendig, de kjører ved PR uansett

✅ Remove yarn test on commit

---

src/components/__tests__/navbar.test.tsx
src/components/bedpres-preview.tsx
src/components/color-mode-button.tsx
src/components/footer.tsx
src/components/student-group-section.tsx

♿️ Fix accessibility issues from Lighthouse

---

src/components/seo.tsx
src/pages/_document.tsx

Nå er nettsiden web app capable på iOS.

:sparkles: iOS web app capable

---

README.md

Byttet til adressen til mailingslisten, så eventuelle mailer blir sendt til alle.

💬 Change email in README

---

src/components/layout.tsx

Litt lat løsning kanskje, men la til ekstra mellomrom mellom body og footer. Denne funker nok midlertidig.

Footer overflow fix

---

.github/workflows/cypress_test.yaml
Dockerfile
src/components/entry-box.tsx
src/components/entry-overview.tsx
src/components/job-advert-overview.tsx
src/components/minute-list.tsx
src/components/student-group-section.tsx
src/lib/api/happening.ts
src/lib/api/index.ts
src/lib/api/job-advert.ts
src/lib/api/minute.ts
src/lib/api/post.ts
src/lib/api/registration.ts
src/lib/api/student-group.ts
src/lib/api/types.ts
src/pages/bedpres/[slug].tsx
src/pages/bedpres/index.tsx
src/pages/event/[slug].tsx
src/pages/event/index.tsx
src/pages/for-studenter/[slug].tsx
src/pages/for-studenter/index.tsx
src/pages/index.tsx
src/pages/jobs/[slug].tsx
src/pages/om-oss.tsx
src/pages/posts/[slug].tsx
src/pages/posts/index.tsx
src/pages/registration/[slug].tsx

Alle static pages skal nå feile i build. Server side pages gir fortsatt en error til brukeren om de failer.

🥅 Remove error handling for static pages

---

src/components/calendar-popup.tsx
src/components/happening-meta-info.tsx

* laget en "legg til i kalender" modal.
* lagt til kalender linker for google, outlook og yahoo.
* lagt til nedlastningslink til .ics fil (fil som kan importeres til andre kalendere)

feature: add to calendar modal.

---

cypress.json
cypress/integration/registration-deletion.spec.ts
src/components/registration-row.tsx
src/lib/api/registration.ts
src/lib/utils.ts
src/pages/registration/[slug].tsx

Om man sletter en påmelding, vil neste person på venteliste rykke opp.
Det er en liten "tutorial" øverst på siden om man trykker på "Hvordan
funker denne listen?".

✨ Add ability to delete registrations 

---

src/components/header-logo.tsx

Integral update to website integrity

---

src/components/happening-meta-info.tsx

🐛 Fix empty reduce error

---

.env.example
.github/workflows/cypress_test.yaml
Dockerfile
README.md
docker-compose.yaml
src/lib/api/api.ts

Trenger ikke SANITY_TOKEN lenger 🤙

🔧 Change to public dataset and CDN

---

src/components/navbar.tsx
src/pages/profile.tsx

Login siden ser litt penere ut

---

src/components/form-question.tsx
src/components/form-term.tsx
src/components/profile-info.tsx
src/components/registration-form.tsx
src/lib/api/decoders.ts
src/lib/api/index.ts
src/lib/api/types.ts
src/lib/api/user.ts
src/pages/api/user/index.ts
src/pages/profile.tsx

Var noe feil med requests fra Next til backend, nå burde alt fungere.
Er en del mer styr pga. vi sender alle requests via Next-serveren.
Nå kan man hvertfall lagre info, og den blir hentet ut igjen av backend.

🐛 Fix backend interop with profile page

---

src/pages/api/user/index.ts
src/pages/profile.tsx

Glemte noen returns i https://github.com/echo-webkom/echo-web-frontend/pull/1052 :)

🐛 Fix request failing on /profile

---

src/components/happening-key-info.tsx
src/pages/index.tsx

Skader ikke å prøve og ha det litt lavere

Update revalidate interval

---

src/components/header-logo.tsx

Match style of post preview author border radius

Update header logo message border radius

---

next.config.js

🔧 Disable next-pwa in dev mode

---

src/components/happening-key-info.tsx

Litt overkill å vise år eller?

Shortened event dates at index

---

src/components/layout.tsx
src/components/student-group-section.tsx
src/lib/api/decoders.ts
src/lib/api/student-group.ts
src/pages/for-studenter/[slug].tsx
src/pages/for-studenter/index.tsx
src/pages/om-oss.tsx

Akkurat nå e bedkom sitt bilde lagt inn på webkom som et eksempel på sizing-en te gruppebildet.

✨Fixed footer overflow, and optional group def + pic

---

src/pages/valg/index.tsx

bruh, glemte å oppdatere dette

🚑 Update valg page
