next.config.js
package.json
src/declarations.d.ts
yarn.lock

Added support for rendering static markdown files with 'markdown-to-jsx'.
Place .md files in public/ and import them using: `import md from '../../public/filename-here.md`.
Then use markdown-to-jsx to render these in a component as such:
```jsx
import React from 'react';
import Markdown from 'markdown-to-jsx';
import MapMarkdownChakra from '../markdown';
import Layout from '../components/layout';
import md from '../../public/filename-here.md';
const TestPage = (): JSX.Element => {
return (
<Layout>
<Markdown options={MapMarkdownChakra}>{md}</Markdown>
</Layout>
);
};
export default TestPage;
```

Support for static markdown files

---

src/lib/api/schema.ts

Changed the query to fetch bedpreses, such that they are sorted by upcoming.

Bedpres sorting by upcoming

---

public/static/om-oss/statutter.md
src/components/__tests__/bedpres-block.test.tsx
src/components/bedpres-block.tsx
src/components/static-info.tsx
src/pages/for-bedrifter.tsx
src/pages/for-studenter.tsx
src/pages/index.tsx
src/pages/om-oss.tsx

Stylized the static info pages. Created a component `StaticInfo` which is used by all static info pages.
This component takes a list of descriptions and a list of markdown files and maps these with the chakra-ui's `Tabs`-component.
Also fixed some responsiveness in index.
- :lipstick: Stylized static info
- :lipstick: Responsive bedpres-block and no min-width for index stack
- :rotating_light: Removed unused import
- :lipstick: Set min-width and max-width for static-info
- :lipstick: Better responsiveness for index
- :art: Fixed tabs responsiveness and size

Static info styling -> develop

---

src/lib/api/bedpres.ts
src/lib/api/schema.ts

Fixed a bug where previous bedpreses would show up in upcoming bedpreses block.
Please see the changed query.

Fixed bug in bedpres-block

---

src/pages/bedpres/[slug].tsx

Fixed a bug where too big integers would be passed to `setTimeout` in `bedpres/[slug].tsx`. This caused the page to constantly fetch data.
The bug would occur when time in ms to bedpres registration starts is bigger than 2^32.

Timeout integer overflow fix

---

renovate.json

Renovate Bot will not create new PR before dependency is stable for amount of days given in "stabilityDays".

🔧 Made Renovate Bot not create PR before stable

---

next.config.js
package.json
yarn.lock

Removed raw-loader, it is deprecated for webpack 5. See [this](https://webpack.js.org/guides/asset-modules/).

Removed raw-loader as it is deprecated

---

src/lib/api/schema.ts
src/pages/om-oss.tsx

Changed the default query such that studentgroups are sorted alphabetically by default

:sparkles: Studentgroups are now ordered alphabetically

---

.eslintrc.js
package.json
src/components/post-list.tsx
src/pages/events/[slug].tsx

lint-staged, lets warnings through by default, so an unused variable now counts as an error, not a warning.

Fixed the unused vars problem

---

package.json
src/lib/api/__tests__/bedpres.test.ts
src/lib/api/__tests__/event.test.ts
src/lib/api/__tests__/minute.test.ts
src/lib/api/__tests__/post.test.ts
src/lib/api/__tests__/student-group.test.ts
yarn.lock

- Remove `dotenv`: Next has built-in support for `.env`-files, see https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables.
- Remove `jest-dom`: `jest-dom` is replaced by `@testing-library/jest-dom`, see https://github.com/mozilla/treeherder/commit/f844f519888c4857752bce6ed10c3dca8ac608ed. 
- Remove `@types/nprogress`: We no longer use `nprogress` and therefore don't need its types. 
- Remove `whatwg-fetch`: Not used.

➖ Remove unused dependencies

---

src/components/happening.tsx

I.e. '**Bare for 1. - 1. trinn**' now shows as '**Bare for 1. trinn**'.

🐛 Fix degree year text when min & max year is same

---

.lintstagedrc.js
package.json

I next.js version 12 kan man linte (sjekke for feil) på individuelle filer. Dette gjør at vi kan bruke `next lint` med `lint-staged` (plugin som linter filer du prøver å commite). Endret på config for å fikse dette. Måtte flytte config fra `package.json` siden man måtte bruke litt Javascript for å gjøre om på input fra `lint-staged`.

🔧 Make next lint work with lint-staged

---

package.json

Man får bare en warning om man har med 'console.log()' i koden når man kjører eslint, endret det til en error så eslint ikke lar deg f.eks. commite med 'console.log()' i koden.

🔧 Fix 'no-console' only producing a warning

---

.github/workflows/rebase.yaml

Man kan ikke bruke GITHUB_TOKEN, siden da kjører ikke workflows som blir trigget av den workflowen som brukte GITHUB_TOKEN (for å forhindre uendelige loops med workflows elns). Derfor så kjører ikke tester på pull requester som blir trigget av rebase-workflowen (siden den bruker GITHUB_TOKEN). La til en Personal Access Token fra min GitHub, burde funke. Kanskje lage en egen Bot-bruker senere så man ikke må bruke personlig GitHub-bruker.

🐛 Fix broken workflow

---

src/components/footer.tsx

Fikk vite at det orginalt sto (at) i echo sin mailadresse for å forhindre spambots å sende mailer, og at dette ikke var et problem lenger.

Byttet (at) med @ i footeren

---

src/pages/bedpres/[slug].tsx

`bedpres/[slug]` refresher constant dersom ikke registration date er definert.
Kjapp hotfix, burde kanskje gjøre registration date required, dersom happening er av type bedpres.
Logikken for dette her er helt ute å kjører, men her er en kjapp hotfix.

🚑 Fixed page refresh

---

src/components/button-link.tsx
src/components/entry-box.tsx
src/components/entry-list.tsx
src/components/hsp.tsx
src/components/post-preview.tsx
src/pages/index.tsx

Forsiden skal nå være mer symmetrisk.
Mange små endringer i koden for å fikse opp i dette. En del av chakra-koden er "optimalisert".  Har fjerna sykt mange `<Center />`-tags, siden de er en ganske hacky måte å sentrere ting på.
Ellers ta en titt på koden.
Should look something like this:
**Note**
hsp-section blir ganske stor med mye tomrom når det er få eller ingen arrangementer siden disse da tar opp like mye plass. Vet ikke om vi vil gjøre noe med dette, eller bare la det stå. Det ser slik ut:

Symmetrical front page sections

---

src/components/info-panels.tsx
src/pages/for-studenter/index.tsx

Funka ikke på `/for-bedrifter` og `/om-oss`. Nå er også `/for-studenter` static igjen.
Er et helvete med router, kopierte han duden her https://github.com/vercel/next.js/discussions/11484#discussioncomment-60563.

🐛 Fix sub routes not working on non-static pages

---

src/components/entry-box.tsx
src/components/entry-list.tsx
src/components/entry-overview.tsx
src/pages/index.tsx

Fikset denne buggen: [https://trello.com/c/9VhqAxc4/90-fikse-direction-bug-for-posts-p%C3%A5-forsiden](https://trello.com/c/9VhqAxc4/90-fikse-direction-bug-for-posts-p%C3%A5-forsiden)
Vi har tidligere bare passet `direction` ned til `entry-list`, selvom den kun er annerledes for posts. Skrev derfor om til at direction er bestemt av `type` i `entry-list`.
Merk: Dersom vi vil bruke `entry-box` med posts på et senere tidspunkt så bør vi nok tenke på refaktorisere hele opplegget her.

Fixed posts direction bug

---

src/components/bedpres-preview.tsx

Dette fikser:
- Logoer til noen bedrifter som har gjennomsiktig bakgrunn får en tilfeldig farge som bakgrunn (se PwC f.eks.).
- Det kommer opp forbokstav med en stygg farge før bilde laster inn.
- Treig lasting av bilder siden vi ikke bruker `next/image`.

⚡️ Change from `Avatar` in `bedpres-preview`

---

src/components/header.tsx
src/components/layout.tsx

Siden paddingen på sidene ville øke med bredden på skjermen ville nettsiden se veldig rar ut på store skjermer (4k+). Sikkert ingen som var plaget av dette, men men.  Nettsiden skal se helt lik ut ellers.
Før:
Etter:
Før (hvis du har urealistisk stor skjerm):

Bedre "responsiveness" på større skjermer

---

src/lib/api/decoders.ts
src/lib/api/happening.ts
src/lib/api/index.ts
src/lib/api/job-advert.ts
src/lib/api/minute.ts
src/lib/api/post.ts
src/lib/api/registration.ts
src/lib/api/student-group.ts
src/lib/api/types.ts

Det ble litt uryddig når alle api modulene implementerte og exporterte sine egne typer og decoders. Samlet alle api type definisjoner i types.ts og alle type decoders i decoders.ts
Måtte legge til en liten eslint ignore før exporten på fem av filene, da "export { ... } from module" i api/index.ts ikke fungerer hvis man bruker default export.

:recycle: Refactored all api types and decoders into their own files

---

src/pages/registration/[slug].tsx

Det er umulig å se hvilken påmelding som blir tatt av ventelisten på arrangementer med flere spotranges. Nå blir de sortert etter venteliste uansett spotrange.

🚑 Sort registrations by waitlist

---

src/pages/index.tsx

Hovedsaklig så events ikke blir gjemt når det er mange (som det er nå).
Økte antall bedpres også så det ser jevnt ut. I stedet for den ekstra
bedpres'en kan vi kanskje ha jobbannonser o.l. der senere.

💄 Increase number of bedpres/events on front page

---

src/lib/api/decoders.ts
src/lib/api/registration.ts

kotlinx.serialization bruker ikke undefined for valgfrie felter.
La til at date kan være null.

👽 Add case that date can be null in backend response 

---

src/pages/api/auth/[...nextauth].ts

Så NextAuth skjønner at du må logge inn på nytt.
1 time er det samme som Feide har. Vet ikke helt hvor vi kan øke dette, men de burde i første omgang matche.

🔧 Set session maxAge to match Feide expire date
